INSERT INTO LENNERT.ACCOUNT_TYPE (ACCOUNT_TYPE_ID, MNEMONIC , ACCOUNT_TYPE_NAME, CREATION_DATE) VALUES(50001,'MILES','Miles','2020-01-01');
INSERT INTO LENNERT.ACCOUNT_TYPE (ACCOUNT_TYPE_ID, MNEMONIC , ACCOUNT_TYPE_NAME, CREATION_DATE) VALUES(50002,'PLAY','AppCurrency','2021-09-21');


INSERT INTO LENNERT.ACCOUNT_TYPE (ACCOUNT_TYPE_ID, MNEMONIC , ACCOUNT_TYPE_NAME, CREATION_DATE) VALUES(50001,'MILES','Miles','2020-01-01');
INSERT INTO LENNERT.ACCOUNT_TYPE (ACCOUNT_TYPE_ID, MNEMONIC , ACCOUNT_TYPE_NAME, CREATION_DATE) VALUES(50002,'PLAY','AppCurrency','2021-09-21');

INSERT INTO LENNERT.MEMBER_ACCOUNT(MEMBER_ID, MEMBER_Username, ACCOUNT_BALANCE) VALUES(1,'MIKE',50.55);
INSERT INTO LENNERT.MEMBER_ACCOUNT(MEMBER_ID, MEMBER_Username, ACCOUNT_BALANCE) VALUES(2,'MATT',50.55);